### ISSUE TITLE
Why not self-service PayPal buttons?

### ISSUE THREAD

**Issue by paulproteus** [bridgefoundry/operations#44]
I was reading the `paypal-button.md` file, and I wondered - can we tell people what to customize, and stop requiring a round-trip to a staff member?

**Comment by dianaluepke** [comment]
If I'm understanding the question correctly, I think the answer is "no."  My guess is that you're hoping there's a way to have the same block of code for the button and just insert the program name in the right spot into the code, or something along those general lines, yes? It's true that there's only one unique bit in each block of button code, but it's an ID that I have to create in the PayPal account and then the system knows that ID translates to a bunch of settings and labels. The only way to generate a new button is to have direct access to the PayPal account. This is probably just as well, since we can only provide buttons to Chapters and Bridges that have signed volunteer agreements, so we probably need that "round trip to a staff member" anyway.

Did I understand the question correctly?

**Comment by kinseydurhamgrace** [comment]
We have a documented, manual process where users can create a PayPal button. It cannot be self service.
